### ISSUE TITLE
Does this exist ?

### ISSUE THREAD

**Issue by darrenahunter** [ionic-team/cordova-splash-generator#1]
Hi Max

Just checking whether this utility actually exists.

Thanks for ionic and everything

Darren

**Comment by darrynten** [comment]
This would be great

**Comment by iolson** [comment]
Would also be highly interested in this!

**Comment by ghost** [comment]
Me too

**Comment by LunarDevelopment** [comment]
:+1:

**Comment by adamdbradley** [comment]
Greetings @darrenahunter!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
